version: '3.9'

services:
  backend:
    build: .
    container_name: backend-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
