version: '3.8'

services:
  users-service:
    build: ./user-service
    container_name: backend-users-service
    ports:
      - "3500:3500"
    environment:
      - ACCOUNT_SERVICE_URL=http://backend-accounts-service:3600
    volumes:
      - ./user-service/data:/app/data   

  accounts-service:
    build: ./account-service
    container_name: backend-accounts-service
    ports:
      - "3600:3600"
    volumes:
      - ./account-service/data:/app/data

  cards-service:
    build: ./cards-service
    container_name: backend-cards-service
    ports:
      - "3602:3602"
    volumes:
      - ./cards-service/data:/app/data
