version: '3.8'

services:
  users-service:
    build:
      context: ./user-service
    ports:
      - "3500:3500"
    restart: always

  accounts-service:
    build:
      context: ./account-service
    ports:
      - "3600:3600"
    depends_on:
      - users-service    # Acá estaba mal el nombre
    restart: always

  cards-service:
    build:
      context: ./cards-service
    ports:
      - "3602:3602"
    depends_on:
      - accounts-service
    restart: always

